name: verify-conformance
on:
  pull_request: {}
  workflow_dispatch: {}
jobs:
  verify-conformance:
    runs-on: ubuntu-latest
    steps:
      - name: verify-conformance
        env:
          GITHUB_TOKEN: ${{ github.token }}
        run: |
          docker run --rm \
            --workdir /github/workspace \
            -e GITHUB_TOKEN -e GITHUB_EVENT_PATH=/github/workflow/event.json \
            -v "$PWD":"/github/workspace" \
            -v "/home/runner/work/_temp/_github_workflow":"/github/workflow" \
              ghcr.io/cncf-infra/verify-conformance/action:latest
